// ---------- Current teams (shared by alt-structure.html and alt-suggestions.html) ----------
// parent: which box the team hangs from ('om-1', 'om-2' or 'top').
// color:  header colour of the team table ('purple' or 'orange').
// Each member: [id, name, role, flag?]
//   flag 'check'  = read from a low-res screenshot, please verify
//   flag 'teal' / 'pink' = row highlight carried over from the original chart
const teams = [
  {
    id: 'logic-lab', name: 'Logic Lab', parent: 'om-1', color: 'purple',
    members: [
      ['15404', 'Md. Tofayel Islam', 'Front End Developer', 'check'],
      ['16020', 'Rathon Roy', 'Front End Developer', 'check'],
      ['15406', 'Sraual Chowhan', 'Front End Developer', 'check'],
      ['15570', 'Md. Jahidul Islam', 'Mobile App Developer', 'check'],
      ['15358', 'Ferdous Hossain Sojib', 'Mobile App Developer', 'check'],
      ['16048', 'Shahed Noor', 'Mobile App Developer', 'check'],
      ['15661', 'Md. Tomiz Uddin', 'Backend Developer', 'check'],
      ['37066', 'Muhammad Irfan', 'Backend Developer', 'check'],
      ['37073', 'Md. Naimul Hasan Naeem', 'Backend Developer', 'check'],
      ['37071', 'Khademul Islam', 'Backend Developer', 'check'],
      ['16272', 'Md. Masum Miah', 'Backend Developer', 'check'],
      ['16010', 'Md. Riaz Hossain', 'UI/UX Designer', 'check'],
      ['16066', 'Md. Ibrahim Shimul', 'UI/UX Designer', 'check'],
    ],
  },
  {
    id: 'pixel-pioneers', name: 'Pixel Pioneers', parent: 'om-1', color: 'purple',
    members: [
      ['15312', 'Asifur Rahman Rifat', 'Backend Developer', 'check'],
      ['15303', 'Ismail Hosain', 'Backend Developer', 'check'],
      ['15180', 'Mofizur Rahman', 'Backend Developer', 'check'],
      ['37063', 'Muhammad Syed', 'Backend Developer', 'check'],
      ['15340', 'Md. Nurnabi Miah', 'Mobile App Developer', 'check'],
      ['15874', 'Jubayer Hossain Hridoy', 'Mobile App Developer', 'check'],
      ['16872', 'Jubaer Islam Nahin', 'Mobile App Developer', 'check'],
      ['16606', 'Nazmul Islam', 'Mobile App Developer', 'check'],
      ['15514', 'MD. Monir Hossen Mahin', 'Front End Developer', 'check'],
      ['15484', 'Md. Rabiul Islam', 'Front End Developer', 'check'],
      ['15732', 'Md. Sufal', 'Front End Developer', 'check'],
      ['15400', 'Md. Hafizur Rahman Shawon', 'UI/UX Designer', 'check'],
      ['16000', 'Md. Rias Miah', 'UI/UX Designer', 'check'],
    ],
  },
  {
    id: 'data-wizard', name: 'Data Wizard', parent: 'om-1', color: 'orange',
    members: [
      ['15284', 'Rabiul Hassan', 'Mobile App Developer', 'check'],
      ['15876', 'Ajijul Hoque', 'Mobile App Developer', 'check'],
      ['15453', 'Md. Ibrahim Khalil', 'Mobile App Developer', 'check'],
      ['15337', 'Ahmad Habib', 'Mobile App Developer', 'check'],
      ['15485', 'Tofiqul Islam', 'Front End Developer', 'check'],
      ['15845', 'Md. Alimuzzaman', 'Front End Developer', 'check'],
      ['16888', 'MD Khairul Islam', 'Front End Developer', 'check'],
      ['15301', 'Md Mizanur Rahman', 'Backend Developer', 'check'],
      ['15802', 'Sadman Sakib', 'Backend Developer', 'check'],
      ['16855', 'Mahfuzul Islam', 'Backend Developer', 'check'],
      ['16012', 'Swadin Sarkar', 'Backend Developer', 'check'],
      ['16818', 'Ridoan Kabir', 'Backend Developer', 'check'],
      ['15281', 'MD. Mofizur Rahman', 'UI/UX Designer', 'check'],
      ['15570', 'Mushfiqur Rahman Islam', 'UI/UX Designer', 'check'],
    ],
  },
  {
    id: 'stack-masters', name: 'Stack Masters', parent: 'om-2', color: 'orange',
    members: [
      ['15287', 'Md. Hilal Ahmed Rony', 'Mobile App Developer', 'check'],
      ['16884', 'Md Kayzul Ahmed', 'Mobile App Developer', 'check'],
      ['15386', 'Md. Arifur Rahman', 'Mobile App Developer', 'check'],
      ['16075', 'Forhad Ali', 'Mobile App Developer', 'check'],
      ['15596', 'Md. Mahfuj Ahmed Bishal', 'Front End Developer', 'check'],
      ['15758', 'Zobayer Hosen', 'Front End Developer', 'check'],
      ['16410', 'MD. Monir Hossen Mamun', 'Front End Developer', 'check'],
      ['15628', 'Md. Abul Basher Shagor', 'UI/UX Designer', 'check'],
      ['15857', 'MD. Al-Amin', 'UI/UX Designer', 'check'],
      ['37067', 'Sakhawat Hossain', 'Backend Developer', 'check'],
      ['16707', 'Hannan Sarkar', 'Backend Developer', 'check'],
      ['16892', 'Mahbube Alam Prosad', 'Backend Developer', 'check'],
      ['16382', 'Habibullah Hinsi', 'Backend Developer', 'check'],
      ['16309', 'Md. Sazzad Hossain', 'Backend Developer', 'check'],
    ],
  },
  {
    id: 'codehydra', name: 'CodeHydra', parent: 'om-2', color: 'orange',
    members: [
      ['15534', 'Md. Badsha', 'Django', 'check'],
      ['15909', 'Md Harun Or Rashid', 'Django', 'check'],
      ['15600', 'Md Moninul Islam', 'Django', 'check'],
      ['15870', 'Rezaul Haque Riaz', 'Django', 'check'],
      ['15907', 'Md. Sakhawat Hossain', 'Django', 'check'],
      ['15858', 'Kawsar Mahabbat', 'Django', 'check'],
      ['15859', 'Al Amin Islam', 'Django', 'check'],
      ['16567', 'SK Habib Mahmood', 'UI/UX Designer', 'check'],
      ['16807', 'Asif Alam Simanto', 'UI/UX Designer', 'check'],
      ['15547', 'Rajeeb Tanjid Antor', 'Mobile App Developer', 'check'],
      ['15347', 'Md. Zobayer Hasan Nayem', 'Mobile App Developer', 'check'],
      ['15885', 'Rabiul Haque', 'MERN', 'check'],
      ['15757', 'Asaduzzaman Hisam', 'MERN', 'check'],
      ['16816', 'Abul Hasnat', 'MERN', 'check'],
      ['15864', 'Rashedul Islam', 'MERN', 'check'],
      ['16076', 'Md Tayeb', 'MERN', 'check'],
      ['15866', 'Sheikh Redwan Ahmed', 'MERN', 'check'],
    ],
  },
  {
    id: 'dev-ninja', name: 'Dev Ninja', parent: 'om-2', color: 'orange',
    members: [
      ['16345', 'Md. Ebadul Islam Rifat', 'n8n', 'check'],
      ['16343', 'Nazmul Islam Nahid', 'n8n', 'check'],
      ['16950', 'Md. Rabiul Islam Roman', 'n8n', 'check'],
      ['16917', 'Shuvo Chandra', 'n8n', 'check'],
      ['13600', 'Md. Monirul Islam', 'n8n', 'check'],
      ['10713', 'Sheikh Md. Salman Farsi', 'AI', 'check'],
      ['16933', 'Anukul Chandra', 'AI', 'check'],
      ['37044', 'MD Abdul Hai Shoraj', 'Front End Developer · n8n', 'check'],
    ],
  },
  {
    id: 'dotify', name: 'Dotify', parent: 'top', color: 'purple',
    members: [
      ['16135', 'Md. Najmul Hossain Rajib', 'Front End Developer', 'check'],
      ['16209', 'Md. Solaiman', 'Front End Developer', 'teal'],
      ['15458', 'Md Farzid Ahmed', 'Mobile App Developer', 'pink'],
      ['15250', 'Alauddin', 'Backend Developer', 'pink'],
      ['37088', 'Fatema Akther Prianka', 'Backend Developer', 'pink'],
      ['16898', 'Md. Shakhawat Hossain', 'Front End Developer', 'check'],
      ['16821', 'Md. Athik Foisal', 'UI/UX Designer', 'pink'],
      ['16630', 'Farhan Shahriar Chayon', 'Django', 'check'],
    ],
  },
];
