/* =========================================================
   1. ROLE NOTES – the text shown in the small note card.
      One entry per kind of role; edit the wording here.
   ========================================================= */
const NOTES = {
  gm: {
    abbr: 'GM',
    label: 'General Manager',
    short: 'Oversees organizational direction, sales, FSD, CMS, and high-level performance metrics.',
    tasks: [
      '07 KAM overall status check',
      'Escalation Group Check',
      'Manage Sales + FSD + CMS',
      'Review Delivery Performance',
      'Review Overall Performance',
      'Receive Delivery & Cancel Data',
      'Communication With Sales',
      'Check Profile Health',
      'Profile Audit',
      'Client Message Pass & Receive',
    ],
  },
  agm: {
    abbr: 'AGM',
    label: 'Assistant General Manager',
    short: 'Assists the GM in monitoring sales, operations, profile health, delivery data, and deadlines.',
    tasks: [
      '07 KAM overall status check',
      'Escalation Group Check',
      'Manage Sales + FSD + CMS',
      'Review Delivery Performance',
      'Review Overall Performance',
      'Receive Delivery & Cancel Data',
      'Communication With Sales',
      'Check Profile Health',
      'Profile Audit',
      'Project Deadline Check',
      'Client Message Pass & Receive',
    ],
  },
  sales: {
    abbr: 'SALES',
    label: 'Sales Department',
    short: 'Brings in new client projects, communicates requirements with management, and hands over project scopes to the Project Coordinator.',
    tasks: [
      'Manage Sales + FSD + CMS',
      'Communication With Sales',
      'Client Message Pass & Receive',
      '07 KAM overall status check',
      'Escalation Group Check',
      'Handover Project To FSD / PC',
      'Review Delivery & Cancel Data',
    ],
  },
  pc: {
    abbr: 'PC',
    label: 'Project Coordinator',
    short: 'Assigns projects to FSD, monitors Operations Managers, tracks delivery progress, and audits projects.',
    tasks: [
      '07 KAM overall status check',
      'Escalation Group Check',
      'Assign Project To FSD',
      'Review Operation Manager',
      'Collect Delivery & Cancel Data',
      'Communication With Sales',
      'Profile Audit',
      'Project Audit',
      'Project Deadline Check',
      'Client Message Pass & Receive',
      'Project Tracker',
    ],
  },
  om: {
    abbr: 'OP',
    label: 'Operation Manager',
    short: 'Manages Project Managers and Special Team, reviews delivery data, and handles project tracking and urgent escalations.',
    tasks: [
      '07 KAM overall status check',
      'Escalation Group Check',
      'Manage Project Manager + Special',
      'Review Project Manager',
      'Collect Delivery & Cancel Data & Review',
      'Communication With Sales',
      'Project Audit',
      'Project Deadline Check',
      'Project Order Sheet Update',
      'Client Message Pass & Receive',
      'Client Meeting (In Case Of Emergency)',
      'Task Manager',
      'Project Tracker',
      'Support Message Check And Write',
    ],
  },
  pm: {
    abbr: 'PM',
    label: 'Project Manager',
    short: 'Manages development teams, assigns developer tasks, updates project sheets, and leads client communication.',
    tasks: [
      '07 KAM overall status check',
      'Escalation Group Check',
      'Manage Teams + Special',
      'Review Team Performance',
      'Generate Delivery & Cancel Data',
      'Communication With Sales',
      'Project Audit',
      'Project Deadline Check',
      'Project Order Sheet Update',
      'Client Message Pass & Receive',
      'Client Meeting',
      'Assign Task',
      'Project Tracker',
    ],
  },
  apm: {
    abbr: 'APM',
    label: 'Assistant Project Manager',
    short: 'Supports the Project Manager with day-to-day project work, updates and follow-ups so the PM can focus on clients and delivery.',
    tasks: [
      'Project Tracker Update',
      'Project Order Sheet Update',
      'Project Deadline Check',
      'Generate Update Message',
      'Client Message Pass & Receive',
      'Follow Up On Developer Tasks',
      'Support PM In Client Meetings',
    ],
  },
  spt: {
    abbr: 'SPDev',
    label: 'Special Dev / Stack Leader',
    short: 'Delivers rapid & high-priority projects, trains developers, performs QA on stacks, and checks source code.',
    tasks: [
      'Project Deadline Check',
      'Generate Update Message',
      'Check Summary',
      'Complete Task',
      'QA Stacks Work',
      'Update Github & Source Code Check + Other',
      'Trainer',
      'Work On Rapid Project & Important',
    ],
  },
  dev: {
    abbr: 'DEV',
    label: 'Developer',
    short: 'Completes assigned features and tasks, updates GitHub/source code, checks summaries, and generates progress updates.',
    tasks: [
      'Project Deadline Check',
      'Generate Update Message',
      'Check Summary',
      'Complete Task',
      'Update Github & Source Code Check',
    ],
  },
};
